alias musescore='./MuseScore-3.6.2.548021370-x86_64.AppImage'
alias muse='./MuseScore-3.6.2.548021370-x86_64.AppImage'
alias py='f(){ python3.9 "$1";  unset -f f; }; f'
alias python='f(){ python3.9 "$1";  unset -f f; }; f'
alias sublime='f(){ subl "$1";  unset -f f; }; f'
alias bat='f(){ batcat "$1";  unset -f f; }; f'
alias new='gnome-terminal'
alias pipes='pipes.sh'
alias .d='bash ~/scripts/.datescript'
alias retro='cool-retro-term --fullscreen'
alias neofetch='neofetch --ascii ascii'
alias lt='command ls -t --color=auto'
alias la='command ls -a --color=auto'
alias ll='command ls -l --color=auto'
alias lta='command ls -la --color=auto'
alias lla='command ls -la --color=auto'
alias llta='command ls -lta --color=auto'
alias aptup='sudo apt-get update && sudo apt-get upgrade'
alias ..='cd ..'
alias clr='clear; ./startup'
